# Generated by Django 3.2.8 on 2022-01-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='estimatedother',
            name='suggested_quantity_limit_estimated_other',
        ),
        migrations.RemoveConstraint(
            model_name='estimatedother',
            name='quantity_limit_estimated_other',
        ),
        migrations.AddConstraint(
            model_name='estimatedother',
            constraint=models.CheckConstraint(check=models.Q(('suggested_quantity__gte', 0.0)), name='suggested_quantity_limit_estimated_other'),
        ),
        migrations.AddConstraint(
            model_name='estimatedother',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0.0)), name='quantity_limit_estimated_other'),
        ),
    ]
